# Generated by Django 3.2.24 on 2024-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240219_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('Department Manager', 'Department Manager'), ('Store Manager', 'Store Manager')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Department Manager', 'Department Manager'), ('Store Manager', 'Store Manager')], max_length=50, unique=True),
        ),
    ]
