# Generated by Django 3.2.24 on 2024-02-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240220_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Department Manager', 'Department Manager'), ('Store Manager', 'Store Manager')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('Department Manager', 'Department Manager'), ('Store Manager', 'Store Manager')], default='Store Manager', max_length=50),
        ),
    ]
